# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a756d939f747b3404648ca3a1a269825"
name = "greenlight-dev"
application_url = "https://greenlightdev.sundialwire.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_assigned_fulfillment_orders,read_customers,read_draft_orders,read_merchant_managed_fulfillment_orders,read_order_edits,read_orders,read_product_feeds,read_product_listings,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_customers,write_draft_orders,write_merchant_managed_fulfillment_orders,write_order_edits,write_orders,write_product_feeds,write_product_listings,write_products,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [ "https://greenlightdev.sundialwire.com/auth/callback" ]
